name: Shell Commands

on: [pull_request, workflow_dispatch]

jobs:
  run-shell-command: 
     runs-on: ubuntu-latest
     steps:
       - name: Echo a String
         run: echo "Hello World"

       - name: multiline script
         run: |
           node -v
           npm -v

       - name: Python Command
         shell: python
         run: |
           import platform
           print (platform.processor())    

  add-delay:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 15 secs
        run: sleep 15

  run-bash-command: 
     runs-on: windows-latest
     needs: [run-shell-command, add-delay]
     steps:
       - name: Directory Powershell
         run: Get-Location

       - name: Directory Bash
         run: pwd
         shell: bash
