name: test matrix
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    
    - run: echo ${{ matrix.project }}
    
    - run: echo ${{ matrix.config }}
    
    - name: Simple JS Action
      id : greet
      uses: actions/hello-world-javascript-action@v1
      with: 
        who-to-greet: ${{ matrix.project }}

    - name: Log Greeting Time
      run: echo "${{ steps.greet.outputs.time }}"
